services:
  db:
    image: postgres:15
    container_name: pomo-stamp-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: pomo-stamp-app
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/mydb?schema=public
    ports:
      - "3000:3000"
    command: >
      sh -c "npx prisma migrate deploy &&
             npx prisma generate &&
             npm run dev"

volumes:
  postgres_data:
